name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493
      - name: Set up Python
        uses: actions/setup-python@5db1cf9a59fb97c40a68accab29236f0da7e94db
        with:
          python-version: '3.12'
      - name: Install uv
        run: pipx install uv
      - name: Sync deps
        run: uv sync --python 3.12
      - name: Ruff check
        run: uv run ruff check .
      - name: Ruff format check
        run: uv run ruff format --check .

  tests-and-sonar:
    name: Tests + SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install uv
        run: pipx install uv
      - name: Sync deps (with dev)
        run: uv sync --python 3.12
      - name: Run tests with coverage
        run: |
          uv run pytest \
            --cov=page_analyzer --cov=app \
            --cov-report=xml:coverage.xml
      - name: SonarQubeScan
        uses: SonarSource/sonarqube-scan-action@01850e2590cc09ed26831056406ae1525aa41ad5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
